// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFProject.DB.Data;

namespace WPFProject.Migrations
{
    [DbContext(typeof(MovieCatalogContext))]
    [Migration("20210212191022_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("MoviePlatform", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "PlatformsId");

                    b.HasIndex("PlatformsId");

                    b.ToTable("MoviePlatform");
                });

            modelBuilder.Entity("MovieRating", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("RatingsId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "RatingsId");

                    b.HasIndex("RatingsId");

                    b.ToTable("MovieRating");
                });

            modelBuilder.Entity("WPFProject.DB.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Komedia"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Akcja"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Science fiction"
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Romans"
                        },
                        new
                        {
                            Id = 6,
                            GenreName = "Dramat"
                        },
                        new
                        {
                            Id = 7,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            GenreName = "Kryminał"
                        },
                        new
                        {
                            Id = 9,
                            GenreName = "Inny"
                        });
                });

            modelBuilder.Entity("WPFProject.DB.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("WPFProject.DB.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlatformName = "Netflix"
                        },
                        new
                        {
                            Id = 2,
                            PlatformName = "HBO"
                        },
                        new
                        {
                            Id = 3,
                            PlatformName = "Disney+"
                        },
                        new
                        {
                            Id = 4,
                            PlatformName = "Canal+"
                        },
                        new
                        {
                            Id = 5,
                            PlatformName = "CDA"
                        },
                        new
                        {
                            Id = 6,
                            PlatformName = "Player"
                        },
                        new
                        {
                            Id = 7,
                            PlatformName = "Inne"
                        });
                });

            modelBuilder.Entity("WPFProject.DB.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RatingName = "Nieporozumienie",
                            RatingValue = 1
                        },
                        new
                        {
                            Id = 2,
                            RatingName = "Ujdzie",
                            RatingValue = 2
                        },
                        new
                        {
                            Id = 3,
                            RatingName = "Średni",
                            RatingValue = 3
                        },
                        new
                        {
                            Id = 4,
                            RatingName = "Dobry",
                            RatingValue = 4
                        },
                        new
                        {
                            Id = 5,
                            RatingName = "Świetny",
                            RatingValue = 5
                        });
                });

            modelBuilder.Entity("WPFProject.DB.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("WPFProject.DB.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFProject.DB.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoviePlatform", b =>
                {
                    b.HasOne("WPFProject.DB.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFProject.DB.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieRating", b =>
                {
                    b.HasOne("WPFProject.DB.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFProject.DB.Models.Rating", null)
                        .WithMany()
                        .HasForeignKey("RatingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WPFProject.DB.Models.Wishlist", b =>
                {
                    b.HasOne("WPFProject.DB.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
